export const SUCCESS = "SUCCESS";
export const WARNING = "WARNING";
export const ERROR = "ERROR";
export const INFO = "INFO";

export const GET_ALLCREDENTIALS = "GET_ALLCREDENTIALS";
export const ADD_NEWCREDENTIAL = "ADD_NEWCREDENTIAL";
export const DELETE_CREDENTIAL = "DELETE_CREDENTIAL";

export const OPEN_DIALOG = "OPEN_DIALOG";
export const CLOSE_DIALOG = "CLOSE_DIALOG";
export const REGISTER_CREDENTIAL = "REGISTER_CREDENTIAL";
